[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  REACT_APP_SERVER_ENDPOINT = "https://short-music-data.alexnorton.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
